annonsorsvillkor:
  title: "Annonsörsvillkor"
  content: |
    ## Villkor för annonsörer

    Här är våra villkor för annonsörer:

    1. *Första villkoret* är viktigt.
    2. **Andra villkoret** är också viktigt.
    3. Tredje villkoret är mindre viktigt.

    För mer information, vänligen kontakta oss.

integritetspolicy:
  title: "Integritetspolicy"
  content: |
    ## Vår integritetspolicy

    Vi värnar om din integritet:

    - Vi samlar in minimal data
    - Vi delar **aldrig** din information
    - Du kan *alltid* begära att få din data raderad

    ### Kontakta oss

    Om du har frågor, vänligen maila privacy@example.com

anvandarvillkor:
  title: "Användarvillkor"
  content: |
    ## Användarvillkor

    Genom att använda vår tjänst godkänner du följande:

    1. Att följa våra community-riktlinjer
    2. Att inte missbruka tjänsten
    3. Att respektera andra användare

    **Viktigt:** Brott mot dessa villkor kan leda till avstängning.

cookies:
  title: "Cookies"
  content: |
    ## Vår cookie-policy

    Vi använder cookies för att:

    - Förbättra användarupplevelsen
    - Analysera trafik
    - Personalisera innehåll

    Du kan *alltid* välja att stänga av cookies i din webbläsare.
